/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace org.openstars.core.bigset.Generic
{
  public enum TErrorCode
  {
    EGood = 0,
    ENoRootMeta = 1,
    ECouldNotConnectMetadata = 2,
    ECouldNotConnectIDGen = 3,
    ECouldNotConnectSmallSet = 4,
    ECouldNotConnectRootMetaMapping = 5,
    EItemNotExisted = 100,
    EUnknownException = 10,
    EBigSetNotExisted = 101,
    EBigSetCreated = 102,
    EBigSetAlreadyExisted = 103,
    EBigSetAssigned = 104,
  }
}
