/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using Thrift;
using Thrift.Collections;

using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


namespace org.openstars.core.bigset.Generic
{

  public partial class TNeedSplitInfo : TBase
  {
    private long _metaID;
    private long _parentID;
    private int _childCount;
    private bool _isSmallSet;

    public long MetaID
    {
      get
      {
        return _metaID;
      }
      set
      {
        __isset.metaID = true;
        this._metaID = value;
      }
    }

    public long ParentID
    {
      get
      {
        return _parentID;
      }
      set
      {
        __isset.parentID = true;
        this._parentID = value;
      }
    }

    public int ChildCount
    {
      get
      {
        return _childCount;
      }
      set
      {
        __isset.childCount = true;
        this._childCount = value;
      }
    }

    public bool IsSmallSet
    {
      get
      {
        return _isSmallSet;
      }
      set
      {
        __isset.isSmallSet = true;
        this._isSmallSet = value;
      }
    }


    public Isset __isset;
    public struct Isset
    {
      public bool metaID;
      public bool parentID;
      public bool childCount;
      public bool isSmallSet;
    }

    public TNeedSplitInfo()
    {
    }

    public async Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        await iprot.ReadStructBeginAsync(cancellationToken);
        while (true)
        {
          field = await iprot.ReadFieldBeginAsync(cancellationToken);
          if (field.Type == TType.Stop)
          {
            break;
          }

          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.I64)
              {
                MetaID = await iprot.ReadI64Async(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 2:
              if (field.Type == TType.I64)
              {
                ParentID = await iprot.ReadI64Async(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 3:
              if (field.Type == TType.I32)
              {
                ChildCount = await iprot.ReadI32Async(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 4:
              if (field.Type == TType.Bool)
              {
                IsSmallSet = await iprot.ReadBoolAsync(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            default: 
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              break;
          }

          await iprot.ReadFieldEndAsync(cancellationToken);
        }

        await iprot.ReadStructEndAsync(cancellationToken);
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public async Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
    {
      oprot.IncrementRecursionDepth();
      try
      {
        var struc = new TStruct("TNeedSplitInfo");
        await oprot.WriteStructBeginAsync(struc, cancellationToken);
        var field = new TField();
        if (__isset.metaID)
        {
          field.Name = "metaID";
          field.Type = TType.I64;
          field.ID = 1;
          await oprot.WriteFieldBeginAsync(field, cancellationToken);
          await oprot.WriteI64Async(MetaID, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if (__isset.parentID)
        {
          field.Name = "parentID";
          field.Type = TType.I64;
          field.ID = 2;
          await oprot.WriteFieldBeginAsync(field, cancellationToken);
          await oprot.WriteI64Async(ParentID, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if (__isset.childCount)
        {
          field.Name = "childCount";
          field.Type = TType.I32;
          field.ID = 3;
          await oprot.WriteFieldBeginAsync(field, cancellationToken);
          await oprot.WriteI32Async(ChildCount, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if (__isset.isSmallSet)
        {
          field.Name = "isSmallSet";
          field.Type = TType.Bool;
          field.ID = 4;
          await oprot.WriteFieldBeginAsync(field, cancellationToken);
          await oprot.WriteBoolAsync(IsSmallSet, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        await oprot.WriteFieldStopAsync(cancellationToken);
        await oprot.WriteStructEndAsync(cancellationToken);
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override bool Equals(object that)
    {
      var other = that as TNeedSplitInfo;
      if (other == null) return false;
      if (ReferenceEquals(this, other)) return true;
      return ((__isset.metaID == other.__isset.metaID) && ((!__isset.metaID) || (System.Object.Equals(MetaID, other.MetaID))))
        && ((__isset.parentID == other.__isset.parentID) && ((!__isset.parentID) || (System.Object.Equals(ParentID, other.ParentID))))
        && ((__isset.childCount == other.__isset.childCount) && ((!__isset.childCount) || (System.Object.Equals(ChildCount, other.ChildCount))))
        && ((__isset.isSmallSet == other.__isset.isSmallSet) && ((!__isset.isSmallSet) || (System.Object.Equals(IsSmallSet, other.IsSmallSet))));
    }

    public override int GetHashCode() {
      int hashcode = 157;
      unchecked {
        if(__isset.metaID)
          hashcode = (hashcode * 397) + MetaID.GetHashCode();
        if(__isset.parentID)
          hashcode = (hashcode * 397) + ParentID.GetHashCode();
        if(__isset.childCount)
          hashcode = (hashcode * 397) + ChildCount.GetHashCode();
        if(__isset.isSmallSet)
          hashcode = (hashcode * 397) + IsSmallSet.GetHashCode();
      }
      return hashcode;
    }

    public override string ToString()
    {
      var sb = new StringBuilder("TNeedSplitInfo(");
      bool __first = true;
      if (__isset.metaID)
      {
        if(!__first) { sb.Append(", "); }
        __first = false;
        sb.Append("MetaID: ");
        sb.Append(MetaID);
      }
      if (__isset.parentID)
      {
        if(!__first) { sb.Append(", "); }
        __first = false;
        sb.Append("ParentID: ");
        sb.Append(ParentID);
      }
      if (__isset.childCount)
      {
        if(!__first) { sb.Append(", "); }
        __first = false;
        sb.Append("ChildCount: ");
        sb.Append(ChildCount);
      }
      if (__isset.isSmallSet)
      {
        if(!__first) { sb.Append(", "); }
        __first = false;
        sb.Append("IsSmallSet: ");
        sb.Append(IsSmallSet);
      }
      sb.Append(")");
      return sb.ToString();
    }
  }

}
