/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using Thrift;
using Thrift.Collections;

using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


namespace org.openstars.core.bigset.Generic
{

  public partial class TPutItemResult : TBase
  {
    private TErrorCode _error;
    private bool _ok;
    private TItem _oldItem;

    /// <summary>
    /// 
    /// <seealso cref="TErrorCode"/>
    /// </summary>
    public TErrorCode Error
    {
      get
      {
        return _error;
      }
      set
      {
        __isset.error = true;
        this._error = value;
      }
    }

    public bool Ok
    {
      get
      {
        return _ok;
      }
      set
      {
        __isset.ok = true;
        this._ok = value;
      }
    }

    public TItem OldItem
    {
      get
      {
        return _oldItem;
      }
      set
      {
        __isset.oldItem = true;
        this._oldItem = value;
      }
    }


    public Isset __isset;
    public struct Isset
    {
      public bool error;
      public bool ok;
      public bool oldItem;
    }

    public TPutItemResult()
    {
    }

    public async Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        await iprot.ReadStructBeginAsync(cancellationToken);
        while (true)
        {
          field = await iprot.ReadFieldBeginAsync(cancellationToken);
          if (field.Type == TType.Stop)
          {
            break;
          }

          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.I32)
              {
                Error = (TErrorCode)await iprot.ReadI32Async(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 2:
              if (field.Type == TType.Bool)
              {
                Ok = await iprot.ReadBoolAsync(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 3:
              if (field.Type == TType.Struct)
              {
                OldItem = new TItem();
                await OldItem.ReadAsync(iprot, cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            default: 
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              break;
          }

          await iprot.ReadFieldEndAsync(cancellationToken);
        }

        await iprot.ReadStructEndAsync(cancellationToken);
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public async Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
    {
      oprot.IncrementRecursionDepth();
      try
      {
        var struc = new TStruct("TPutItemResult");
        await oprot.WriteStructBeginAsync(struc, cancellationToken);
        var field = new TField();
        if (__isset.error)
        {
          field.Name = "error";
          field.Type = TType.I32;
          field.ID = 1;
          await oprot.WriteFieldBeginAsync(field, cancellationToken);
          await oprot.WriteI32Async((int)Error, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if (__isset.ok)
        {
          field.Name = "ok";
          field.Type = TType.Bool;
          field.ID = 2;
          await oprot.WriteFieldBeginAsync(field, cancellationToken);
          await oprot.WriteBoolAsync(Ok, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if (OldItem != null && __isset.oldItem)
        {
          field.Name = "oldItem";
          field.Type = TType.Struct;
          field.ID = 3;
          await oprot.WriteFieldBeginAsync(field, cancellationToken);
          await OldItem.WriteAsync(oprot, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        await oprot.WriteFieldStopAsync(cancellationToken);
        await oprot.WriteStructEndAsync(cancellationToken);
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override bool Equals(object that)
    {
      var other = that as TPutItemResult;
      if (other == null) return false;
      if (ReferenceEquals(this, other)) return true;
      return ((__isset.error == other.__isset.error) && ((!__isset.error) || (System.Object.Equals(Error, other.Error))))
        && ((__isset.ok == other.__isset.ok) && ((!__isset.ok) || (System.Object.Equals(Ok, other.Ok))))
        && ((__isset.oldItem == other.__isset.oldItem) && ((!__isset.oldItem) || (System.Object.Equals(OldItem, other.OldItem))));
    }

    public override int GetHashCode() {
      int hashcode = 157;
      unchecked {
        if(__isset.error)
          hashcode = (hashcode * 397) + Error.GetHashCode();
        if(__isset.ok)
          hashcode = (hashcode * 397) + Ok.GetHashCode();
        if(__isset.oldItem)
          hashcode = (hashcode * 397) + OldItem.GetHashCode();
      }
      return hashcode;
    }

    public override string ToString()
    {
      var sb = new StringBuilder("TPutItemResult(");
      bool __first = true;
      if (__isset.error)
      {
        if(!__first) { sb.Append(", "); }
        __first = false;
        sb.Append("Error: ");
        sb.Append(Error);
      }
      if (__isset.ok)
      {
        if(!__first) { sb.Append(", "); }
        __first = false;
        sb.Append("Ok: ");
        sb.Append(Ok);
      }
      if (OldItem != null && __isset.oldItem)
      {
        if(!__first) { sb.Append(", "); }
        __first = false;
        sb.Append("OldItem: ");
        sb.Append(OldItem== null ? "<null>" : OldItem.ToString());
      }
      sb.Append(")");
      return sb.ToString();
    }
  }

}
