/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using Thrift;
using Thrift.Collections;

using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


namespace org.openstars.core.bigset.Generic
{

  public partial class TSplitBigSetResult : TBase
  {
    private TErrorCode _error;
    private bool _splited;
    private long _newRootID;
    private byte[] _minItem;
    private long _count;

    /// <summary>
    /// 
    /// <seealso cref="TErrorCode"/>
    /// </summary>
    public TErrorCode Error
    {
      get
      {
        return _error;
      }
      set
      {
        __isset.error = true;
        this._error = value;
      }
    }

    public bool Splited
    {
      get
      {
        return _splited;
      }
      set
      {
        __isset.splited = true;
        this._splited = value;
      }
    }

    public long NewRootID
    {
      get
      {
        return _newRootID;
      }
      set
      {
        __isset.newRootID = true;
        this._newRootID = value;
      }
    }

    public byte[] MinItem
    {
      get
      {
        return _minItem;
      }
      set
      {
        __isset.minItem = true;
        this._minItem = value;
      }
    }

    public long Count
    {
      get
      {
        return _count;
      }
      set
      {
        __isset.count = true;
        this._count = value;
      }
    }


    public Isset __isset;
    public struct Isset
    {
      public bool error;
      public bool splited;
      public bool newRootID;
      public bool minItem;
      public bool count;
    }

    public TSplitBigSetResult()
    {
    }

    public async Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        await iprot.ReadStructBeginAsync(cancellationToken);
        while (true)
        {
          field = await iprot.ReadFieldBeginAsync(cancellationToken);
          if (field.Type == TType.Stop)
          {
            break;
          }

          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.I32)
              {
                Error = (TErrorCode)await iprot.ReadI32Async(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 2:
              if (field.Type == TType.Bool)
              {
                Splited = await iprot.ReadBoolAsync(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 3:
              if (field.Type == TType.I64)
              {
                NewRootID = await iprot.ReadI64Async(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 4:
              if (field.Type == TType.String)
              {
                MinItem = await iprot.ReadBinaryAsync(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 5:
              if (field.Type == TType.I64)
              {
                Count = await iprot.ReadI64Async(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            default: 
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              break;
          }

          await iprot.ReadFieldEndAsync(cancellationToken);
        }

        await iprot.ReadStructEndAsync(cancellationToken);
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public async Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
    {
      oprot.IncrementRecursionDepth();
      try
      {
        var struc = new TStruct("TSplitBigSetResult");
        await oprot.WriteStructBeginAsync(struc, cancellationToken);
        var field = new TField();
        if (__isset.error)
        {
          field.Name = "error";
          field.Type = TType.I32;
          field.ID = 1;
          await oprot.WriteFieldBeginAsync(field, cancellationToken);
          await oprot.WriteI32Async((int)Error, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if (__isset.splited)
        {
          field.Name = "splited";
          field.Type = TType.Bool;
          field.ID = 2;
          await oprot.WriteFieldBeginAsync(field, cancellationToken);
          await oprot.WriteBoolAsync(Splited, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if (__isset.newRootID)
        {
          field.Name = "newRootID";
          field.Type = TType.I64;
          field.ID = 3;
          await oprot.WriteFieldBeginAsync(field, cancellationToken);
          await oprot.WriteI64Async(NewRootID, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if (MinItem != null && __isset.minItem)
        {
          field.Name = "minItem";
          field.Type = TType.String;
          field.ID = 4;
          await oprot.WriteFieldBeginAsync(field, cancellationToken);
          await oprot.WriteBinaryAsync(MinItem, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if (__isset.count)
        {
          field.Name = "count";
          field.Type = TType.I64;
          field.ID = 5;
          await oprot.WriteFieldBeginAsync(field, cancellationToken);
          await oprot.WriteI64Async(Count, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        await oprot.WriteFieldStopAsync(cancellationToken);
        await oprot.WriteStructEndAsync(cancellationToken);
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override bool Equals(object that)
    {
      var other = that as TSplitBigSetResult;
      if (other == null) return false;
      if (ReferenceEquals(this, other)) return true;
      return ((__isset.error == other.__isset.error) && ((!__isset.error) || (System.Object.Equals(Error, other.Error))))
        && ((__isset.splited == other.__isset.splited) && ((!__isset.splited) || (System.Object.Equals(Splited, other.Splited))))
        && ((__isset.newRootID == other.__isset.newRootID) && ((!__isset.newRootID) || (System.Object.Equals(NewRootID, other.NewRootID))))
        && ((__isset.minItem == other.__isset.minItem) && ((!__isset.minItem) || (System.Object.Equals(MinItem, other.MinItem))))
        && ((__isset.count == other.__isset.count) && ((!__isset.count) || (System.Object.Equals(Count, other.Count))));
    }

    public override int GetHashCode() {
      int hashcode = 157;
      unchecked {
        if(__isset.error)
          hashcode = (hashcode * 397) + Error.GetHashCode();
        if(__isset.splited)
          hashcode = (hashcode * 397) + Splited.GetHashCode();
        if(__isset.newRootID)
          hashcode = (hashcode * 397) + NewRootID.GetHashCode();
        if(__isset.minItem)
          hashcode = (hashcode * 397) + MinItem.GetHashCode();
        if(__isset.count)
          hashcode = (hashcode * 397) + Count.GetHashCode();
      }
      return hashcode;
    }

    public override string ToString()
    {
      var sb = new StringBuilder("TSplitBigSetResult(");
      bool __first = true;
      if (__isset.error)
      {
        if(!__first) { sb.Append(", "); }
        __first = false;
        sb.Append("Error: ");
        sb.Append(Error);
      }
      if (__isset.splited)
      {
        if(!__first) { sb.Append(", "); }
        __first = false;
        sb.Append("Splited: ");
        sb.Append(Splited);
      }
      if (__isset.newRootID)
      {
        if(!__first) { sb.Append(", "); }
        __first = false;
        sb.Append("NewRootID: ");
        sb.Append(NewRootID);
      }
      if (MinItem != null && __isset.minItem)
      {
        if(!__first) { sb.Append(", "); }
        __first = false;
        sb.Append("MinItem: ");
        sb.Append(MinItem);
      }
      if (__isset.count)
      {
        if(!__first) { sb.Append(", "); }
        __first = false;
        sb.Append("Count: ");
        sb.Append(Count);
      }
      sb.Append(")");
      return sb.ToString();
    }
  }

}
